// gendocs generates TOOLS.md from the tool registry.
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/atla-digital/mcp-gitlab-lite/internal/tools"
	"github.com/atla-digital/mcp-gitlab-lite/internal/tools/descriptions"
)

func main() {
	d := descriptions.Load()
	entries := tools.All(d)

	var b strings.Builder
	b.WriteString("# GitLab MCP — Tool Reference\n\n")
	b.WriteString("> Auto-generated by `go generate ./...` — do not edit manually.\n\n")
	b.WriteString("---\n\n")

	// TOC
	b.WriteString("## Contents\n\n")
	seen := map[string]bool{}
	for _, e := range entries {
		cat := string(e.Category)
		if !seen[cat] {
			anchor := strings.ToLower(strings.ReplaceAll(cat, " ", "-"))
			fmt.Fprintf(&b, "- [%s](#%s)\n", cat, anchor)
			seen[cat] = true
		}
	}
	b.WriteString("\n---\n\n")

	// Body
	currentCat := ""
	for _, e := range entries {
		cat := string(e.Category)
		if cat != currentCat {
			currentCat = cat
			fmt.Fprintf(&b, "## %s\n\n", cat)
		}

		name := e.Tool.Name
		fmt.Fprintf(&b, "### `%s`\n\n", name)

		if desc := d.Tool(name); desc != "" {
			fmt.Fprintf(&b, "%s\n\n", desc)
		}

		props := e.Tool.InputSchema.Properties
		if len(props) == 0 {
			continue
		}

		b.WriteString("| Parameter | Required | Type | Description |\n")
		b.WriteString("|-----------|----------|------|-------------|\n")

		required := e.Tool.InputSchema.Required
		isRequired := func(p string) bool {
			for _, r := range required {
				if r == p {
					return true
				}
			}
			return false
		}

		propType := func(v any) string {
			if m, ok := v.(map[string]any); ok {
				if t, ok := m["type"].(string); ok {
					return t
				}
			}
			return "string"
		}

		for _, pname := range required {
			fmt.Fprintf(&b, "| `%s` | ✓ | `%s` | %s |\n", pname, propType(props[pname]), d.Param(name, pname))
		}

		optionals := make([]string, 0, len(props))
		for pname := range props {
			if !isRequired(pname) {
				optionals = append(optionals, pname)
			}
		}
		sort.Strings(optionals)

		for _, pname := range optionals {
			fmt.Fprintf(&b, "| `%s` | | `%s` | %s |\n", pname, propType(props[pname]), d.Param(name, pname))
		}
		b.WriteString("\n")
	}

	if err := os.WriteFile("TOOLS.md", []byte(b.String()), 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "write error: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("wrote TOOLS.md (%d tools)\n", len(entries))
}
